version: '3.9'

services:
  db:
    image: postgres:16
    container_name: notes-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: notes-backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SECRET: ${SECRET}
      EXPIRATION: ${EXPIRATION}
    ports:
      - "${APP_PORT}:8080"
    restart: always

volumes:
  db_data: