spring:
  datasource:
    url: jdbc:postgresql://localhost:9999/testDB
    username: qwerty
    password: qwerty
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true
server:
  port: 9999